services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
      API_RESEND_KEY: ${API_RESEND_KEY}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install && npm run start:docker && npm run start"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # migrate:
  #   build: .
  #   command: npx prisma migrate dev --name init
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   depends_on:
  #     db:
  #       condition: service_healthy

  # seed:
  #   build: .
  #   command: npx prisma db seed
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  postgres_data: